
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "UserWS", targetNamespace = "http://services.webservicesoap.sn.esp/", wsdlLocation = "http://localhost:8080/ws/user?wsdl")
public class UserWS
    extends Service
{

    private static final URL USERWS_WSDL_LOCATION;
    private static final WebServiceException USERWS_EXCEPTION;
    private static final QName USERWS_QNAME = new QName("http://services.webservicesoap.sn.esp/", "UserWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/user?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERWS_WSDL_LOCATION = url;
        USERWS_EXCEPTION = e;
    }

    public UserWS() {
        super(__getWsdlLocation(), USERWS_QNAME);
    }

    public UserWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERWS_QNAME, features);
    }

    public UserWS(URL wsdlLocation) {
        super(wsdlLocation, USERWS_QNAME);
    }

    public UserWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERWS_QNAME, features);
    }

    public UserWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserService
     */
    @WebEndpoint(name = "UserServicePort")
    public UserService getUserServicePort() {
        return super.getPort(new QName("http://services.webservicesoap.sn.esp/", "UserServicePort"), UserService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserService
     */
    @WebEndpoint(name = "UserServicePort")
    public UserService getUserServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.webservicesoap.sn.esp/", "UserServicePort"), UserService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERWS_EXCEPTION!= null) {
            throw USERWS_EXCEPTION;
        }
        return USERWS_WSDL_LOCATION;
    }

}
